Feature/support config
kungze/quic-tun pull request #10
Opened 2022-07-21 02:53 UTC by lp-learn

2022-07-21 03:58 UTC, lp-learn commented
let's go

2022-07-21 07:52 UTC, jeffyjf requested changes
README 文档也需做相应的更改

2022-07-21 07:52 UTC, jeffyjf commented on cmd/quictun-client/main.go
> +	rand.Seed(time.Now().UTC().UnixNano())
这一行有什么作用呢？

2022-07-21 07:52 UTC, jeffyjf commented on pkg/app/config.go
> +// loadConfig reads in config file and ENV variables if set.
不需要的代码就删除吧

2022-07-21 07:52 UTC, jeffyjf commented on pkg/util/homedir/homedir.go
> +package homedir
package utils 会比较好，没必要每个 util 都有一个 pkg

2022-07-21 07:52 UTC, jeffyjf commented on configs/quictun-client.yaml
> +    insecure-skip-verify: false
这个和 server 的保持一致的风格，可以改成 verify-server

2022-07-21 07:52 UTC, jeffyjf commented on configs/quictun-client.yaml
> +# quic-tun-client 全配置
文件里面的注释尝试用英语写一下吧

2022-07-21 07:52 UTC, jeffyjf commented on pkg/term/term.go
> +package term
这个放在 app 的 pkg 吧，感觉没必要单独一个 pkg

2022-07-21 08:05 UTC, jeffyjf requested changes

2022-07-21 08:05 UTC, jeffyjf commented on pkg/json/json.go
> +//go:build jsoniter
这个 pkg 貌似没有用到，而且这么包装一下的目的是什么呢？感觉没有必要。

2022-07-21 08:05 UTC, jeffyjf commented on pkg/cli/flag.go
> +package flag
按照惯例，package 后面应该和目录名保持一样，而且这个代码直接放在 pkg/app 里面就可以了

2022-07-21 08:05 UTC, jeffyjf commented on pkg/flag/flags.go
> +// Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
这个文件的内容看着和 pkg/cli/flag.go 的很像，确定不是重复代码？

2022-07-21 08:25 UTC, lp-learn commented on pkg/flag/flags.go
> +// Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
确实

2022-07-21 08:39 UTC, lp-learn commented on pkg/json/json.go
> +//go:build jsoniter
这个最开始应该是参考的 gin 项目 https://github.com/gin-gonic/gin/tree/master/internal/json
可以通过 go build -tags=jsoniter 命令进行编译生效

2022-07-21 08:55 UTC, lp-learn commented on cmd/quictun-client/main.go
> +	rand.Seed(time.Now().UTC().UnixNano())
这个设置随机数生成种子，好像现在项目里可能用不到，用的时候再加吧

2022-07-21 08:56 UTC, lp-learn commented on pkg/app/config.go
> +// loadConfig reads in config file and ENV variables if set.
ok

2022-07-21 08:56 UTC, lp-learn commented on pkg/util/homedir/homedir.go
> +package homedir
ok

2022-07-21 08:58 UTC, lp-learn commented on configs/quictun-client.yaml
> +    insecure-skip-verify: false
ok

2022-07-21 08:59 UTC, jeffyjf commented on pkg/json/json.go
> +//go:build jsoniter
这个是干嘛的呢？我们会在什么场景下用到呢？

2022-07-21 09:36 UTC, lp-learn commented on pkg/json/json.go
> +//go:build jsoniter
这个目前这块用到了 https://github.com/kungze/quic-tun/blob/001ef937d0107c2048314c705ed67141721d1f50/pkg/app/app.go#L209

2022-07-21 09:37 UTC, lp-learn commented on pkg/term/term.go
> +package term
ok

2022-07-21 13:53 UTC, lp-learn commented on pkg/cli/flag.go
> +package flag
ok

2022-07-21 13:56 UTC, lp-learn commented on configs/quictun-client.yaml
> +# quic-tun-client 全配置
ok，有一些还没想好怎么描述

2022-07-22 00:43 UTC, jeffyjf commented
貌似越改越乱了，建议分为 3 个 commit 来完成：1、整理命令行及命令行参数；2、引入 viper 配置文件；3、重构 log 相关代码

2022-07-31 14:18 UTC, closed without merging