feat: Optimize command line code
kungze/quic-tun pull request #13
Opened 2022-07-22 07:07 UTC by lp-learn

2022-07-23 02:26 UTC, jeffyjf requested changes

2022-07-23 02:26 UTC, jeffyjf commented on client/app.go
> +package client
这个文件和 server/app.go 几乎一样，可不可以考虑放在 pkg/app 里面呢

2022-07-23 02:26 UTC, jeffyjf commented on client/client.go
> +	log "k8s.io/klog/v2"
log 框架的改变应该在之后的 commit

2022-07-23 02:26 UTC, jeffyjf commented on client/client.go
> +	return preparedClient{s}
这个 preparedClient 貌似没有做任何事情啊

2022-07-23 02:26 UTC, jeffyjf commented on client/client.go
> +	session, err := quic.DialAddr(c.ClientOptions.ServerEndpointSocket, c.TlsConfig, &quic.Config{KeepAlivePeriod: 15 * time.Second})
这个时间可以作为一个配置项，而且 15 秒貌似太短了

2022-07-23 02:26 UTC, jeffyjf commented on pkg/app/globalflags.go
> +package app
注意文件命名方式的统一 global_flags.go

2022-07-23 02:35 UTC, jeffyjf requested changes

2022-07-23 02:35 UTC, jeffyjf commented on client/config/config.go
> +	return &Config{opts}, nil
这个永远没有错误返回，包装这一层还有必要吗？

2022-07-23 02:35 UTC, jeffyjf commented on client/config/config.go
> +	return &Config{opts}, nil
我觉得这个文件都可以删除，没有做任何事情

2022-07-23 02:49 UTC, jeffyjf requested changes

2022-07-23 02:49 UTC, jeffyjf commented on pkg/app/cmd.go
> +package app
这个文件里的函数，我没发现在其他地方有调用

2022-07-23 02:56 UTC, jeffyjf requested changes
在仔细检查一下，patch 中有大量无用代码

2022-07-23 02:56 UTC, jeffyjf commented on pkg/app/flags.go
> +func WarnWordSepNormalizeFunc(f *pflag.FlagSet, name string) pflag.NormalizedName {
这个函数貌似没有用到啊

2022-07-25 03:28 UTC, lp-learn commented on pkg/app/flags.go
> +func WarnWordSepNormalizeFunc(f *pflag.FlagSet, name string) pflag.NormalizedName {
是的 我再重新review

2022-07-25 07:07 UTC, lp-learn commented on client/client.go
> +	return preparedClient{s}
嗯这块之后可以放一些中间件的初始化操作，目前没用，先删了吧

2022-07-29 06:19 UTC, closed without merging