Init some common modules
kungze/quic-tun pull request #14
Opened 2022-07-27 06:59 UTC by lp-learn

2022-07-30 06:33 UTC, jeffyjf requested changes

2022-07-30 06:33 UTC, jeffyjf commented on cmd/quictun-client/main.go
> +/*
我觉得这个 main 函数文件还是写在 client/cmd 下吧，没必要单独拿出来一个目录

2022-07-30 06:33 UTC, jeffyjf commented on cmd/quictun-client/main.go
> +func Execute() {
在包装一层 Execute 没有必要，直接 main 函数吧

2022-07-30 06:33 UTC, jeffyjf commented on pkg/options/client.go
> +	VerifyServer         bool   `json:"verify-server"       mapstructure:"verify-server"`
VerifyServer 重命名成 VerifyRemoteEndpoint，server 端也一样，这样 CertFile，KeyFile，VerifyRemoteEndpoint 和 CaFile 可以单独一个文件了，不用 client 和 server 分开写了

2022-07-30 07:16 UTC, lp-learn commented on pkg/options/client.go
> +	VerifyServer         bool   `json:"verify-server"       mapstructure:"verify-server"`
好的 我修改一下

2022-07-31 09:19 UTC, lp-learn commented on cmd/quictun-client/main.go
> +/*
嗯 先不动吧

2022-07-31 09:19 UTC, lp-learn commented on cmd/quictun-client/main.go
> +func Execute() {
ok

2022-08-01 01:40 UTC, jeffyjf approved these changes

2022-08-01 01:41 UTC, jeffyjf commented
总体上代码没什么问题了，就有一个疑问：commit 标题中的 build 和 feat 分别是什么意思呢？

2022-08-01 03:31 UTC, lp-learn commented
这个我是参考项目 https://github.com/angular/angular/blob/main/CONTRIBUTING.md 的提交规范来的。
比如 
feat: A new feature
build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)

2022-08-01 05:35 UTC, merged