Add data traffic statistics code
kungze/quic-tun pull request #20
Opened 2022-09-26 06:47 UTC by caotingv

2022-10-01 03:18 UTC, jeffyjf requested changes

2022-10-01 03:18 UTC, jeffyjf commented on pkg/tunnel/tunnel.go
>  	_, err := io.CopyN(io.MultiWriter(*t.Conn, t.streamCache), *t.Stream, classifier.HeaderLength)
前 1024 个字节也需要统计进去

2022-10-01 03:18 UTC, jeffyjf commented on pkg/tunnel/tunnel.go
> +func copyBuffer(dst io.Writer, src io.Reader, buf []byte, FlowChan chan int64) (written int64, err error) {
返回值 written 应该没有用到

2022-10-01 03:18 UTC, jeffyjf commented on pkg/tunnel/tunnel.go
> +				t.SendTotalFlow = int64(<-sendFlowChan)
需要考虑这个 go 程如何退出

2022-10-01 03:20 UTC, jeffyjf commented
这个 pr 我今天来改一改吧，你可以对照学习一下。

2022-10-01 03:22 UTC, caotingv commented
> 这个 pr 我今天来改一改吧，你可以对照学习一下。
好的，收到。

2022-10-02 06:39 UTC, jeffyjf approved these changes

2022-10-02 06:40 UTC, merged